rg_name                  = "crcdev-rg"
storage_name             = "apcrcdevstorage1"
subscription             = "e0a05e3d-c7c8-4da3-bb86-62e0f43a09ab"
container_name           = "tfstate"
cdnprofile_name          = "crcdevcdnprofile1"
cdnendpoint_name         = "crcdevcdnendpoint1"
cdncustomdomain_name     = "devresume-andrewperlas-com"
cdncustomdomain_hostname = "devresume.andrewperlas.com"